nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Comment Moderation API
            description: Asynchronous comment submission and moderation API
            version: '%env(resolve:REVISION)%'
        servers:
            -   url: http://localhost
                description: Local
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        Health:
            path_patterns:
                - ^/health

        default:
            path_patterns:
                - ^/(?!_(error|wdt|profiler)).*
