security:
    providers:
        jwt:
            lexik_jwt: ~

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        api:
            pattern: ^/
            provider: jwt
            stateless: true
            entry_point: Gsoi\CommentModeration\Infrastructure\Security\JsonAuthenticationEntryPoint
            access_denied_handler: Gsoi\CommentModeration\Infrastructure\Security\JsonAuthenticationEntryPoint
            jwt: ~

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/health$, roles: PUBLIC_ACCESS }
        - { path: ^/doc, roles: PUBLIC_ACCESS }
        - { path: ^/webhooks/facebook/comments$, roles: PUBLIC_ACCESS, methods: [GET, HEAD, POST] }
        - { path: ^/comments$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/comments/moderation/batch$, roles: ROLE_MODERATOR, methods: [POST] }
        - { path: ^/comments/.+/moderation$, roles: ROLE_MODERATOR, methods: [POST] }
        - { path: ^/comments, roles: IS_AUTHENTICATED_FULLY, methods: [GET, HEAD] }
